spring:
  application:
    name: Batch-Poc
  datasource:
    url: jdbc:mysql://localhost:3306/batch-poc
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 9009
logging:
  pattern:
    console: "%d{HH:mm:ss} -> [${spring.application.name}] : %msg%n"